# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Conversion.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 800)
        MainWindow.setMinimumSize(QtCore.QSize(400, 800))
        MainWindow.setMaximumSize(QtCore.QSize(400, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.footButton = QtWidgets.QPushButton(self.centralwidget)
        self.footButton.setGeometry(QtCore.QRect(100, 60, 91, 32))
        self.footButton.setObjectName("footButton")
        self.yardButton = QtWidgets.QPushButton(self.centralwidget)
        self.yardButton.setGeometry(QtCore.QRect(190, 60, 91, 32))
        self.yardButton.setObjectName("yardButton")
        self.mileButton = QtWidgets.QPushButton(self.centralwidget)
        self.mileButton.setGeometry(QtCore.QRect(280, 60, 91, 32))
        self.mileButton.setObjectName("mileButton")
        self.inchesButton = QtWidgets.QPushButton(self.centralwidget)
        self.inchesButton.setGeometry(QtCore.QRect(10, 60, 91, 32))
        self.inchesButton.setObjectName("inchesButton")
        self.resultText = QtWidgets.QLineEdit(self.centralwidget)
        self.resultText.setGeometry(QtCore.QRect(190, 570, 41, 21))
        self.resultText.setObjectName("resultText")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(150, 520, 113, 32))
        self.convertButton.setObjectName("convertButton")
        self.displayText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.displayText.setGeometry(QtCore.QRect(70, 610, 261, 121))
        self.displayText.setObjectName("displayText")
        self.userInput = QtWidgets.QLineEdit(self.centralwidget)
        self.userInput.setGeometry(QtCore.QRect(140, 130, 113, 21))
        self.userInput.setObjectName("userInput")
        self.footButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.footButton_2.setGeometry(QtCore.QRect(100, 460, 91, 32))
        self.footButton_2.setObjectName("footButton_2")
        self.yardButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.yardButton_2.setGeometry(QtCore.QRect(190, 460, 91, 32))
        self.yardButton_2.setObjectName("yardButton_2")
        self.mileButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.mileButton_2.setGeometry(QtCore.QRect(280, 460, 91, 32))
        self.mileButton_2.setObjectName("mileButton_2")
        self.inchesButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.inchesButton_2.setGeometry(QtCore.QRect(10, 460, 91, 32))
        self.inchesButton_2.setObjectName("inchesButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 0, 91, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 130, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 61, 16))
        self.label_3.setObjectName("label_3")
        self.userInput_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.userInput_2.setGeometry(QtCore.QRect(140, 170, 113, 21))
        self.userInput_2.setObjectName("userInput_2")
        self.displayText_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.displayText_2.setGeometry(QtCore.QRect(80, 290, 261, 121))
        self.displayText_2.setObjectName("displayText_2")
        self.calcButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcButton.setGeometry(QtCore.QRect(140, 230, 121, 41))
        self.calcButton.setObjectName("calcButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 430, 21, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.footButton.setText(_translate("MainWindow", "Foot"))
        self.yardButton.setText(_translate("MainWindow", "Yard"))
        self.mileButton.setText(_translate("MainWindow", "Mile"))
        self.inchesButton.setText(_translate("MainWindow", "Inches"))
        self.resultText.setText(_translate("MainWindow", "Result"))
        self.convertButton.setText(_translate("MainWindow", "CONVERT"))
        self.footButton_2.setText(_translate("MainWindow", "Foot"))
        self.yardButton_2.setText(_translate("MainWindow", "Yard"))
        self.mileButton_2.setText(_translate("MainWindow", "Mile"))
        self.inchesButton_2.setText(_translate("MainWindow", "Inches"))
        self.label.setText(_translate("MainWindow", "Area of Rectangle"))
        self.label_2.setText(_translate("MainWindow", "Enter Base"))
        self.label_3.setText(_translate("MainWindow", "Enter Height"))
        self.calcButton.setText(_translate("MainWindow", "Calculate"))
        self.label_4.setText(_translate("MainWindow", "To"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
